### ISSUE TITLE
Could CecMonitor.start be public instead of protected?

### ISSUE THREAD

**Issue by dpkay** [jvanharn/node-hdmi-cec#2]
Hi there!

I am using hdmi-cec with my own wrapper around cec-client (forwarding all incoming requests through the network to another machine that actually runs cec-client). To that end I'm constructing CecMonitor with autostart=false, and then invoke CecMonitor.start manually with a custom argument.

As it stands, autostart=false is not actually that useful since clients can't invoke the start method. I had to locally modify hdmi-cec to allow for this.

Thoughts?
Thanks!
Dominik

**Comment by jvanharn** [comment]
Hey Dominik,

You could always extend the CecMonitor wrapper, and manually pass your instance to the Remote, etc. as constructor arguments and add whatever you would like. (Including a public start method) Would that suffice for your situation? The autostart=false was really meant for people extending the functionality, and help them make that easier.

I could make it public but the idea was to have it eventually only start "jit" when the first event listener gets registered for example. Although as you might have noticed; I have never come around to actually doing that.

Would extending CecMonitor solve your problem?

**Comment by dpkay** [comment]
Yes, you are right! That does resolve my problem. I don't know why I wasn't thinking of it – I suppose I don't do a lot of inheritance in my code. Many thanks for the response (and for building such a clean library)!
